#' Feature Imputation Function
#'
#' This function performs imputation on the features data derived from the featureExtractor function.
#' It uses the Multiple Imputation by Chained Equations (MICE) algorithm to handle missing data.
#' It then standardizes the imputed data and returns the modified input list with the imputed and standardized data.
#'
#' @param extractorList A list generated by the featureExtractor function, containing raw and standardized features, as well as the GAM models.
#'
#' @return A list similar to the input, but with additional elements:
#'    * featuresImp: The result of the imputation process, an object of class "mids".
#'    * featuresImpZ: A data frame of standardized imputed features.
#'    * featuresImpZMat: A data frame of standardized imputed features with person identifiers as row names.
#'
#' @importFrom mice mice complete
#' @importFrom dplyr mutate across everything
#' @importFrom tibble column_to_rownames
#'
#' @examples
#' \dontrun{
#' extractorList <- featureExtractor(df, c("item1", "item2"), "ID", "time")
#' imputedList <- featureImputer(extractorList)
#' }
#' @export

featureImputer <- function(extractorList) {
  # Impute features with mice
  extractorList$featuresImp <- mice(
    extractorList$features,
    m = 1,
    maxit = 50,
    seed = 123
  )

  # Scale the completed imputed features
  extractorList$featuresImpZ <- complete(extractorList$featuresImp) %>%
    mutate(across(c(everything(), -ID), scale))

  # Transform the scaled imputed features to a matrix
  extractorList$featuresImpZMat <- extractorList$featuresImpZ %>%
    column_to_rownames("ID") %>%
    mutate(across(everything(), as.vector))

  # Return the modified extractorList
  return(extractorList)
}
